package com.zain.assistant.actions

/** Every offline/device command Zain understands, independent of any AI provider. */
enum class ActionType {
    CALL_CONTACT,
    OPEN_CONTACTS,
    SEND_SMS,
    OPEN_APP,
    OPEN_CAMERA,
    OPEN_GALLERY,
    OPEN_CHROME,
    OPEN_SETTINGS,
    OPEN_CALCULATOR,
    OPEN_CALENDAR,
    OPEN_CLOCK,
    OPEN_FILES,
    OPEN_WHATSAPP,
    OPEN_YOUTUBE,
    OPEN_MAPS,
    SET_ALARM,
    SET_TIMER,
    CREATE_REMINDER,
    SHOW_DATE,
    SHOW_TIME,
    SHOW_BATTERY,
    SHOW_STORAGE,
    SHOW_RAM,
    SHOW_NETWORK_STATUS,
    FLASHLIGHT_ON,
    FLASHLIGHT_OFF,
    VOLUME_UP,
    VOLUME_DOWN,
    BRIGHTNESS_UP,
    BRIGHTNESS_DOWN,
    READ_NOTIFICATIONS,
    TELL_JOKE,
    SEARCH_WEB,
    UNKNOWN
}
